[project]
icon = "https://ijskoud.dev/assets/svg/logo.svg"
icon_width = "100px"
version = "1.0.0"

[variables]
information = "Automations for personal use."
installation = "I see no reason why you would want to install this."